[package]
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "redis_streams"
version = "0.4.1"

[dependencies]
uuid = { version = "0.8.2", features = ["serde", "v4"] }
